name: flutter_close_app
description: 一款灵活的 Flutter 关闭 App 插件，包含Android 按2次返回关闭，MacOS、iOS、Windows、Linux 一键关闭）
version: 1.0.0
homepage: https://github.com/yy1300326388/flutter_close_app

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
