name: flutter_close_app
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/yy1300326388/flutter_close_app

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
